<!-- formulario de agregar materia -->
 <h1>Ingrese una materia</h1>
<form action="agregar" method="POST">
    <div class="mb-3">
        <label class="form-label">Materia</label>
        <input name="nombre" type="text" class="form-control" id="" placeholder="Ingrese la materia">
    </div>
    <div class="mb-3">
        <label class="form-label">Profesor</label>
        <input name="profesor" type="text" class="form-control" id="" placeholder="Nombre del profesor">
    </div>
        <div class="mb-3">
        <label class="form-label">Carrera</label>
        <input name="carrera" type="text" class="form-control" id="" placeholder="Nombre de carrera">
    </div>
        <div class="mb-3">
        <label class="form-label">Años</label>
        <input name="anios" type="number" class="form-control" id="" placeholder="Duración">
    </div>

    <button type="submit" class="btn btn-success">Añadir</button>
    <!-- <a href="agregar" type="button" class="btn btn-success">Añadir</a> -->

</form>