<h2>Materias</h2>

<table class="pagos">
    <thead>
        <tr style='background-color: yellow;'>
            <th style='padding:5px;text-align:center'>Materia</th>
            <th style='padding:5px;text-align:center'>Profesor</th>
            <th style='padding:5px;text-align:center'>Carrera</th>
            <th style='padding:5px;text-align:center'>Años</th>
        </tr>
    </thead>
    <tbody>
        <button type="submit">Buscar <input type="text" name="search" id=""></button>
        <tr>
            <?php
            foreach  ($materias as $materia) {
            ?>
                <td style='padding:5px;text-align:center'><?php echo $materia->nombre_materia ?></td>
                <td style='padding:5px;text-align:center'><?php echo $materia->profesor ?></td>
                <td style='padding:5px;text-align:center'><?php echo $materia->nombre_carrera ?></td>
                <td style='padding:5px;text-align:center'><?php echo $materia->anios ?></td>
                <td><a href="modificar/<?php echo $materia->id ?>" type="button" class="btn btn-warning">Modificar</a></td>
                <td><a href="eliminar/<?php echo $materia->id ?>" type="button" class="btn btn-danger">Eliminar</a></td>
        </tr>
    <?php } ?>

    </tbody>
</table>